### ISSUE TITLE
Unable to add CancerSeqSim.jl

### ISSUE THREAD

**Issue by adnanakbr** [marcjwilliams1/CancerSeqSim.jl#26]
Hi, 
I am unable to add CancerSeqSim.jl with the following commands in Julia shell:

using Pkg
Pkg.add("CancerSeqSim.jl")

It gives me the following error:

ERROR: The following package names could not be resolved:
 * CancerSeqSim.jl (not found in project, manifest or registry)
Please specify by known `name=uuid`.

I am new to Julia, can you please confirm if the above commands should still be working and what i am doing wrong?

**Comment by marcjwilliams1** [comment]
Hi @adnanakbr, my bad sorry. You don't need the ".jl", ```Pkg.add("CancerSeqSim")``` should work. I've now updated the README

**Comment by adnanakbr** [comment]
perfect, its working now. Thanks a lot for your quick response.
